[tool.poetry]
name = "python"
version = "0.1.0"
description = ""
authors = ["Sean Wu <seanwu1105@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
PySide6 = "^6.0.3"
PyQt6 = "^6.1.0"
PySide2 = "^5.15.2"
PyQt5 = "^5.15.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
pylint = "^2.8.2"
mypy = "^0.812"
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
