name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node

      - name: Install dependencies
        if: steps.release.outputs.release_created
        run: npm ci

      - name: Package VSIX
        if: steps.release.outputs.release_created
        run: npx vsce package

      - name: Publish on Visual Studio Code Extension Marketplace
        if: steps.release.outputs.release_created
        run: npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload VSIX to release assets
        if: steps.release.outputs.release_created
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path:
            vscode-qt-for-python-${{ steps.release.outputs.major }}.${{
            steps.release.outputs.minor }}.${{ steps.release.outputs.patch
            }}.vsix
